name: Torchlight File Update
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_MAIN_SERVER }}
          username: ${{ secrets.FTP_MAIN_USERNAME }}
          password: ${{ secrets.FTP_MAIN_PASS }}
